import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'
import Brand from '@/components/Brand'
import Footer from '@/components/Footer'
import Courses from '@/components/Courses'
import Offers from '@/components/Offers'
import Popular from '@/components/Popular'
import Review from '@/components/Review'
import Connect from '@/components/Connect'
import Faq from '@/components/Faq'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech Life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar  />
      <main>
        <Hero />
        <Brand />
        <Courses />
        <Offers />
        <Popular />
        <Review />
        <Connect />
        <Faq />
      </main>
      <Footer />
    </>
  )
}
